# Generated by Django 5.1.2 on 2024-10-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_cartitem_category_order_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '分類'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cAddr',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.CharField(default='default.jpg', max_length=200, verbose_name='商品圖片'),
        ),
    ]
