# Generated by Django 5.1.2 on 2024-10-31 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_test2_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='用餐日期')),
                ('adult_count', models.PositiveIntegerField(verbose_name='大人人數')),
                ('child_count', models.PositiveIntegerField(verbose_name='小孩人數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='餐廳名稱')),
                ('address', models.TextField(verbose_name='地址')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話號碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('lunch', '午餐'), ('dinner', '晚餐')], max_length=10, verbose_name='餐期')),
                ('slot_time', models.TimeField(verbose_name='時段時間')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='myapp.restaurant', verbose_name='餐廳')),
            ],
            options={
                'verbose_name': '用餐時段',
                'verbose_name_plural': '用餐時段',
                'unique_together': {('restaurant', 'period', 'slot_time')},
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='myapp.restaurant', verbose_name='餐廳'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.timeslot', verbose_name='用餐時段'),
        ),
        migrations.DeleteModel(
            name='test2',
        ),
    ]
