# Generated by Django 4.2.16 on 2024-11-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_reservation_restaurant_timeslot_delete_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='store_img',
            field=models.CharField(default='default.jpg', max_length=200, verbose_name='店家圖片'),
        ),
    ]
