# Generated by Django 5.1.2 on 2024-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_restaurant_store_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='account',
            field=models.CharField(default='null', max_length=30, verbose_name='帳號'),
        ),
    ]
